#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

. .builder

npm install

mkdir target/

mkdir target/pub/

for entry in source/pub.brand/*; do

  copy_entry "$entry" "target/pub/${entry#source/pub.brand/}"
done

for dir in source/*.*/; do
  
  dir="${dir%/}"
  
  name="${dir##*.}"
  
  dir2="${dir#source/}"
  dir2="${dir2%.*}"
  dir2="${dir2//.//}"

  build_js "$dir/$name.js" "target/$dir2/$name.js"
done

echo -e "\nDone"
